import Head from 'next/head'
import Image from 'next/image'


export default function Home() {

  return (
    <>
      <Head>
        <title>Fireship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1 className='text-emerald-700'>Homepage</h1> */}
    </>
  )
}


