import Head from 'next/head'
import React from 'react'

export default function index() {
    return (
        <>
            <Head>
                <title>All Courses</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='mt-[80px] xl:px-[32px] lg:px-[26px] px-[10px] mb-8'>
                <header>
                    <h1 className='font-title md:text-[55px] text-[40px] font-[900] text-center'>
                        COURSES
                    </h1>
                    <p className='font-code md:text-[25px] text-[20px] text-[#b2becd] text-center mt-[-10px]'>challenging multi-step experiences with quizzes and progress-tracking</p>
                </header>
                <div className='lg:mt-[48px] mt-[39px] mb-[76px] mx-auto h-[4px] w-[96px] rounded-md bg-gradient-to-r from-gray-700 to-gray-500'></div>
            </main>
        </>
    )
}
