import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Image from 'next/image';
import BlogCard from '../../components/BlogCard';


export default function Labs({ posts, tags }) {
    return (
        <>
            <Head>
                <title>All Labs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='mt-[80px] xl:px-[32px] lg:px-[26px] px-[10px]'>
                <header>
                    <h1 className='md:text-[48px] text-[39px] font-[700] text-center'>
                        LABS
                    </h1>
                    <p className='md:text-[16px] text-[13px] text-[#b2becd] text-center mt-[-10px]'>single dose video lessons and tutorials</p>
                </header>
                <div className='lg:mt-[48px] mt-[39px] mb-[76px] mx-auto h-[4px] w-[96px] rounded-md bg-gradient-to-r from-gray-700 to-gray-500'></div>

                <div>
                    <ul className='grid grid-cols-1 sm:grid-cols-1 justify-items-center md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 gap-y-[55px]'>
                        {posts.map(post =>
                            <li className="blogCard rounded hover:scale-105 ease-in duration-300 xl:w-full max-w-[400px]" key={post._id}>
                                <BlogCard post={post} tags={tags} />
                            </li>
                        )}
                    </ul>

                </div>
            </main>
        </>
    )
}

export async function getStaticProps() {
    const urlPost = 'https://6730jc99.api.sanity.io/v1/data/query/production?query=*[_type=="post"]'

    const resPost = await fetch(urlPost);
    const resultPost = await resPost.json();
    const posts = resultPost.result;

    const urlTag = 'https://6730jc99.api.sanity.io/v1/data/query/production?query=*[_type=="tag"]'

    const resTag = await fetch(urlTag);
    const resultTag = await resTag.json();
    const tags = resultTag.result;

    return {
        props: {
            posts,
            tags
        },
    }
}

